### ISSUE TITLE
Make failed

### ISSUE THREAD

**Issue by tonyfd** [SeSaMe-NUS/genie#1] opened 2016-09-21 08:00 UTC
Hello, I am Ye Hao from Zhejiang University, China. The project is awesome and thanks for your contributions.
I tried to compile the latest version but I got the following errors:

`yh@TITAN-SERVER:~/workspace/zjusakasu/GPUGENIE-Release$ sudo make

[  2%] Building NVCC (Device) object src/CMakeFiles/GPUGenie.dir/GPUGenie/GPUGenie_generated_FileReader.cu.o
[  5%] Building NVCC (Device) object src/CMakeFiles/GPUGenie.dir/GPUGenie/GPUGenie_generated_genie_errors.cu.o
[  8%] Building NVCC (Device) object src/CMakeFiles/GPUGenie.dir/GPUGenie/GPUGenie_generated_inv_list.cu.o
[ 11%] Building NVCC (Device) object src/CMakeFiles/GPUGenie.dir/GPUGenie/GPUGenie_generated_inv_table.cu.o
[ 13%] Building NVCC (Device) object src/CMakeFiles/GPUGenie.dir/GPUGenie/GPUGenie_generated_query.cu.o
[ 16%] Building NVCC (Device) object src/CMakeFiles/GPUGenie.dir/GPUGenie/GPUGenie_generated_match.cu.o
[ 19%] Building NVCC (Device) object src/CMakeFiles/GPUGenie.dir/GPUGenie/GPUGenie_generated_interface.cu.o
[ 22%] Building NVCC (Device) object src/CMakeFiles/GPUGenie.dir/GPUGenie/GPUGenie_generated_knn.cu.o
[ 25%] Building NVCC (Device) object src/CMakeFiles/GPUGenie.dir/GPUGenie/GPUGenie_generated_heap_count.cu.o
Scanning dependencies of target GPUGenie
[ 27%] Building CXX object src/CMakeFiles/GPUGenie.dir/GPUGenie/Logger.cc.o
/home/yh/workspace/zjusakasu/GPUGENIE-Release/src/GPUGenie/Logger.cc: In static member function ¡®static int Logger::log(int, const char_, ...)¡¯:
/home/yh/workspace/zjusakasu/GPUGENIE-Release/src/GPUGenie/Logger.cc:107:49: warning: format not a string literal and no format arguments [-Wformat-security]
  fprintf(_logger()->logger->logfile, currentTime);
                                                 ^
/home/yh/workspace/zjusakasu/GPUGENIE-Release/src/GPUGenie/Logger.cc:113:45: warning: format not a string literal and no format arguments [-Wformat-security]
  fprintf(_logger()->logger->logfile, message);
                                             ^
/home/yh/workspace/zjusakasu/GPUGENIE-Release/src/GPUGenie/Logger.cc:118:17: warning: format not a string literal and no format arguments [-Wformat-security]
   printf(message);
                 ^
[ 30%] Building CXX object src/CMakeFiles/GPUGenie.dir/GPUGenie/Timing.cc.o
[ 33%] Linking CXX static library ../lib/libGPUGenie.a
[ 33%] Built target GPUGenie
[ 36%] Building NVCC (Device) object test/CMakeFiles/test_12_subsequence_search_binary_input.dir/test_12_subsequence_search_binary_input_generated_test_12.cu.o
Scanning dependencies of target test_12_subsequence_search_binary_input
[ 38%] Linking CXX executable ../bin/test_12_subsequence_search_binary_input
/home/yh/workspace/zjusakasu/GPUGENIE-Release/lib/libGPUGenie.a(GPUGenie_generated_inv_table.cu.o): In function `void boost::serialization::throw_exception<boost::archive::archive_exception>(boost::archive::archive_exception const&)':
/usr/local/include/boost/serialization/throw_exception.hpp:36: undefined reference to`boost::archive::archive_exception::archive_exception(boost::archive::archive_exception const&)'
/home/yh/workspace/zjusakasu/GPUGENIE-Release/lib/libGPUGenie.a(GPUGenie_generated_inv_table.cu.o): In function `void boost::archive::binary_iarchive_impl<boost::archive::binary_iarchive, char, std::char_traits<char> >::load_override<boost::archive::class_name_type>(boost::archive::class_name_type&)':
/usr/local/include/boost/archive/binary_iarchive_impl.hpp:58: undefined reference to`boost::archive::basic_binary_iarchiveboost::archive::binary_iarchive::load_override(boost::archive::class_name_type&)'
collect2: error: ld returned 1 exit status
make[2]: *_\* [bin/test_12_subsequence_search_binary_input] Error 1
make[1]: **\* [test/CMakeFiles/test_12_subsequence_search_binary_input.dir/all] Error 2
make: **\* [all] Error 2
`

My cmake version is 2.8.12.2, cuda version is 7.0, g++ 11 is included. I have tried boost 1.60 and 1.61 but neither passed due to the same error as above. 
Could you please show me some advice to solve the problem? Thanks a lot.

**Comment by YuejiYang** [comment] 2016-09-21 13:01
The problem lies in boost. There is a header file missing in your boost distribution. The file is "pfto.hpp", which include the dependency you need.  Below is the source code of pfto.hpp. Just put this file in the director : /usr/local/include/boost/serialization/   , and re-compile the code.

```
#ifndef BOOST_SERIALIZATION_PFTO_HPP
#define BOOST_SERIALIZATION_PFTO_HPP

// MS compatible compilers support #pragma once
#if defined(_MSC_VER) && (_MSC_VER >= 1020)
# pragma once
#endif

/////////1/////////2/////////3/////////4/////////5/////////6/////////7/////////8
// pfto.hpp: workarounds for compilers which have problems supporting
// Partial Function Template Ordering (PFTO).

// (C) Copyright 2002 Robert Ramey - http://www.rrsd.com . 
// Use, modification and distribution is subject to the Boost Software
// License, Version 1.0. (See accompanying file LICENSE_1_0.txt or copy at
// http://www.boost.org/LICENSE_1_0.txt)

//  See http://www.boost.org/libs/serialization for updates, documentation, and revision history.
// PFTO version is used to specify the last argument of certain functions
// Function it is used to support  compilers that fail to support correct Partial 
// Template Ordering
#include <boost/config.hpp>

// some compilers can use an exta argument and use function overloading
// to choose desired function.  This extra argument is long in the default
// function implementation and int for the rest.  The function is called
// with an int argument.  This first attempts to match functions with an
// int argument before the default one (with a long argument).  This is
// known to function with VC 6.0. On other compilers this fails (Borland)
// or causes other problems (GCC).  note: this 

#if defined(BOOST_NO_FUNCTION_TEMPLATE_ORDERING)
    #define BOOST_PFTO long
#else
    #define BOOST_PFTO
#endif

// here's another approach.  Rather than use a default function - make sure
// there is no default at all by requiring that all function invocations
// have a "wrapped" argument type.  This solves a problem with VC 6.0
// (and perhaps others) while implementing templated constructors.

namespace boost {
namespace serialization {

template<class T>
struct pfto_wrapper {
    const T & t;
    operator const T & (){
        return t;
    }
    pfto_wrapper (const T & rhs) : t(rhs) {}
};

template<class T>
pfto_wrapper< T > make_pfto_wrapper(const T & t, BOOST_PFTO int){
    return pfto_wrapper< T >(t);
}

template<class T>
pfto_wrapper< T > make_pfto_wrapper(const pfto_wrapper< T > & t, int){
    return t;
}

} // namespace serialization
} // namespace boost

#ifdef BOOST_NO_FUNCTION_TEMPLATE_ORDERING
    #define BOOST_PFTO_WRAPPER(T) \
        boost::serialization::pfto_wrapper< T >
    #define BOOST_MAKE_PFTO_WRAPPER(t) \
        boost::serialization::make_pfto_wrapper(t, 0)
#else
    #define BOOST_PFTO_WRAPPER(T) T
    #define BOOST_MAKE_PFTO_WRAPPER(t) t
#endif

#endif // BOOST_SERIALIZATION_PFTO_HPP





```

**Comment by tonyfd** [comment] 2016-09-22 07:01
Thanks for your help! I have tried with boost 1.60 and 1.61 on two servers but it did not work... The error is the same as before. Anyway, I am going to use the previous version which do not need boost 1.60 at the moment~ :D

**Comment by YuejiYang** [comment] 2016-09-22 07:22
Hi, I suggest you better check the directory /usr/local/include/boost/serialization, There should be exact 76 header files plus one directory. The header files' names are as follows:
`
access.hpp
archive_input_unordered_map.hpp
archive_input_unordered_set.hpp
array.hpp
assume_abstract.hpp
base_object.hpp
binary_object.hpp
bitset.hpp
boost_unordered_map.hpp
boost_unordered_set.hpp
collection_size_type.hpp
collections_load_imp.hpp
collections_save_imp.hpp
collection_traits.hpp
complex.hpp
config.hpp
deque.hpp
ephemeral.hpp
export.hpp
extended_type_info.hpp
extended_type_info_no_rtti.hpp
extended_type_info_typeid.hpp
factory.hpp
force_include.hpp
forward_list.hpp
hash_collections_load_imp.hpp
hash_collections_save_imp.hpp
hash_map.hpp
hash_set.hpp
is_bitwise_serializable.hpp
item_version_type.hpp
level_enum.hpp
level.hpp
list.hpp
map.hpp
nvp.hpp
optional.hpp
**pfto.hpp**
priority_queue.hpp
queue.hpp
scoped_ptr.hpp
serialization.hpp
set.hpp
shared_ptr_132.hpp
shared_ptr_helper.hpp
shared_ptr.hpp
singleton.hpp
slist.hpp
smart_cast.hpp
split_free.hpp
split_member.hpp
stack.hpp
state_saver.hpp
static_warning.hpp
string.hpp
strong_typedef.hpp
throw_exception.hpp
tracking_enum.hpp
tracking.hpp
traits.hpp
type_info_implementation.hpp
unique_ptr.hpp
unordered_collections_load_imp.hpp
unordered_collections_save_imp.hpp
unordered_map.hpp
unordered_set.hpp
utility.hpp
valarray.hpp
variant.hpp
vector_135.hpp
vector.hpp
version.hpp
void_cast_fwd.hpp
void_cast.hpp
weak_ptr.hpp
wrapper.hpp
`

If you do have all these files, make sure /usr/local/lib is in the search path for dynamic libraries. You can run ldconfig to update the ld.so.conf.cache.

And after your installation of boost, you'd better check the boost version, by a simple c++ programs as follows:
`
#include <boost/version.hpp>
#include <iostream>

using namespace std;

int main()
{
    cout << BOOST_VERSION << endl;
    return 0;
}
`
It is possible that your installation does not override the past version of boost.

To install a fresh boost:
you can first delete /usr/local/include/boost , as well as /usr/local/lib/libboost*, 
And then under boost root directory(untar from what you've downloaded), run sudo ./b2 install.
After this, run ldconfig to make sure everything is up to date. 

This undefined reference error is caused by some broken dependency chain in boost. Hope this will help. Previous version may contain bugs, so be careful when you use it.

Regrads,
Yueji

**Comment by tonyfd** [comment] 2016-09-22 07:59
Yeah I think so but I just can't figure out where the cause lies. The header files are completed now after I added pfto.hpp. And I do have deleted /usr/local/include/boost and /usr/local/lib/libboost\* every time before I re-install boost. Still the same error...
Thanks a lot~ The previous version runs OK at the moment.

**Comment by YuejiYang** [comment] 2016-09-22 08:09
test/ folder includes better examples for you to refer to.

**Comment by lkrcal** [comment] 2017-06-30 13:53
Completely new CMake configuration is now in place. Closing this issue.

**Closed as completed by lkrcal** 2017-06-30 13:53 UTC
